[project]
name = "manuscript"
description = "Manuscript for a2z-expression"
authors = ["Travis Wrightsman <tw493@cornell.edu>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
build = { cmd = ["typst", "compile", "main.typ", "manuscript.pdf"] }

[dependencies]
# stay on 0.10 until https://github.com/typst/typst/issues/3699 fixed
typst = "0.10.*"
